#config_version=6

slide_player:
  mode_attract_started: attract


show_player:
  mode_attract_started: 
    laneshow:
      show_tokens:
        leds: led-launch, led-save, led-lane-b1

sound_player:
  mode_attract_started:
    SlowMusic:
      bus: music
      loops: 99


