#config_version=6

slide_player:
  mode_attract_started: attract


show_player:
  mode_attract_started: 
    laneshow:
      show_tokens:
        leds: led-bumper-1, led-bumper-2, led-bumper-3


sound_player:
  mode_attract_started:
    SlowMusic:
      bus: music
      loops: 99


