#config_version=6

# Hardware Configuration: Coils

coils:
  # Chain PSOC 2-0-x
  c_sling_right:
    number: 2-0-0
    default_pulse_ms: 15
  c_sling_left:
    number: 2-0-1
    default_pulse_ms: 16
  c_plunger:
    number: 2-0-2
    default_pulse_ms: 21
  c_trough_eject:
    number: 2-0-3
    default_pulse_ms: 25
       
  c_popbumper_1:
    number: 2-0-4
    default_pulse_ms: 17
  c_popbumper_2:
    number: 2-0-5
    default_pulse_ms: 17
  c_popbumper_3:
    number: 2-0-6
    default_pulse_ms: 17
  c_drop:              
    number: 2-0-7
    default_pulse_ms: 25
    
    # Chain PSOC 2-1-x  
    #name:
    #    number: 2-1-0
    #    default_pulse_ms: 25
    #name:
    #    number: 2-1-1
    #    default_pulse_ms: 25
    #name:
    #    number: 2-1-2
    #    default_pulse_ms: 25
    #name:              
    #    number: 2-1-3
    #    default_pulse_ms: 25
    
    #name:              
    #    number: 2-1-4
    #    default_pulse_ms: 25
    #name:              
    #    number: 2-1-5
    #    default_pulse_ms: 25
    #name:              
    #    number: 2-1-6
    #    default_pulse_ms: 25
    #name:              
    #    number: 2-1-7
    #    default_pulse_ms: 25

    # Cobra 0-0- & 1-0-
    #name:              
    #    number: 0-0-8
    #    default_pulse_ms: 25
    #name:
    #    number: 0-0-9
    #    default_pulse_ms: 25
    #name:
    #    number: 0-0-10
    #    default_pulse_ms: 25
    #name:
    #    number: 0-0-11
    #    default_pulse_ms: 25
    #name:
    #    number: 0-0-0
    #    default_pulse_ms: 25
    #name:
    #    number: 0-0-12
    #    default_pulse_ms: 25
    #name:
    #    number: 0-0-13
    #    default_pulse_ms: 25
    #name:
    #    number: 0-0-14
    #    default_pulse_ms: 25
    
    #name:
    #    number: 0-0-15
    #    default_pulse_ms: 25
    #name:
    #    number: 0-0-7
    #    default_pulse_ms: 25
    #name:
    #    number: 0-0-6
    #    default_pulse_ms: 25
    #name:
    #    number: 0-0-5
    #    default_pulse_ms: 25
    #name:
    #    number: 0-0-4
    #    default_pulse_ms: 25
    #name:
    #    number: 0-0-3
    #    default_pulse_ms: 25
    #name:
    #    number: 0-0-2
    #    default_pulse_ms: 25
    #name:
    #    number: 0-0-1
    #    default_pulse_ms: 25
    
    #name:
    #    number: 1-0-0
    #    default_pulse_ms: 25
    #name:
    #    number: 1-0-7
    #    default_pulse_ms: 25
    #name:
    #    number: 1-0-6
    #    default_pulse_ms: 25
    #name:
    #    number: 1-0-5
    #    default_pulse_ms: 25
    #name:
    #    number: 1-0-4
    #    default_pulse_ms: 25
    #name:
    #    number: 1-0-3
    #    default_pulse_ms: 25
    #name:
    #    number: 1-0-2
    #    default_pulse_ms: 25
    #name:
    #    number: 1-0-1
    #    default_pulse_ms: 25



